# General Settings
highlighter:            rouge

# Post Settings
permalink:              pretty
paginate:               5
excerpt_separator:      "<!-- more -->"

# Things to include and ignore      
include:                ['.htaccess']
exclude:
- ".editorconfig"
- ".gitignore"
- "bower.json"
- "CNAME"
- "composer.json"
- "CONTRIBUTING.md"
- "DOCS-LICENSE"
- "Gruntfile.js"
- "less"
- "LICENSE"
- "node_modules"
- "package.json"
- "README.md"
- "sauce_browsers.yml"
- "test-infra"
- "Gemfile"
- "Gemfile.lock"
- "public/less"
keep_files:             ['.git','.svn']


# General Info
title:                  "Hello Jekyll"
tagline:                "An unstyled and somewhat opinionated Jekyll boilerplate that utilizes LESS and Grunt."
description:            "An unstyled and somewhat opinionated <a href='http://jekyllrb.com' target='_blank'>Jekyll</a> boilerplate that utilizes LESS and Grunt. Made by <a href='https://twitter.com/itsmeara' target='_blank'>@itsMeAra</a>."
baseurl:                /
url:                    

# Replace with your social info
author:
    name:               'Your Name'
    url:                'https://your-website.com'
    twitter:            '@yourName'
    github:             'yourName'
    gplus:              'XXXXXXXXXXXXXX'  


# Google Analytics     
analytics:
  google: 
    # eg. 'UA-123-12'
    site_id:               'UA-XXX-XX'


# Google Fonts
# eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
google_font:          "Open+Sans:400,700"


# Custom
version:                1.0.0
github:
  repo:                 https://github.com/itsmeara/hello-jekyll
